version: "3"
services:
  mongodb:
    image: "mongo:3-stretch"
    ports:
    - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
    - mongodb
  mongo-express:
    image: "mongo-express:latest"
    ports:
    - "8081:8081"
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on: 
    - "mongo-seed"
    
# useful ENV variables
#    mongo:
#        image: mongo
#        environment:
#            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
#            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
#            - MONGO_INITDB_DATABASE=project
#    mongo-express:
#        image: mongo-express
#        environment:
#            - ME_CONFIG_MONGODB_PORT=27017
#            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
#            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
#            - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
#            - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
#            - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
#            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}